### ISSUE TITLE
Informations érronées

### ISSUE THREAD

**Issue by GoogleCodeExporter** [guenillon/zeybux#116]
```
Plusieurs informations sont erronées :

* Marge / Tableau résumé à revoir car il doit ressortir la marge du marché
        Pour l’instant, on reste avec le tableau Compta_COOP_Marché Zeybux
* Correction des erreurs dans le compte Zeybu (livraisons en crédit !!! )

* Montant en caisse à corriger dans le compte Zeybu


```

Original issue reported on code.google.com by `guenil...@gmail.com` on 15 Jul 2012 at 7:22

**Comment by guenillon** [comment]
Clôture sans action supplémentaire:
* Marge déjà ajoutée
* Les livraisons en crédit corrigées par le #133
* Correction du montant dans les données. par de problème de code.
