### ISSUE TITLE
Inclure IE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [guenillon/zeybux#182]
```
Permettre l'utilisation du zeybux avec IE.
A partir de la version IE 9

Migrer Jquery dans la branche 2



```

Original issue reported on code.google.com by `guenil...@gmail.com` on 16 Feb 2014 at 9:06

**Comment by guenillon** [comment]
Autorisation de Microsoft Edge et IE 11, les autres navigateurs Microsoft n'étant plus supportés.

Pas de Migration Jquery.

Fermeture de la version sans JS.
