### ISSUE TITLE
Installation zeybux - paramétrage.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [guenillon/zeybux#211]
```
Ajouter l'ensemble des tables de paramétrage à l'installation du zeybux.

Prendre en compte le cas du typepaiement réservation qui doit être à 0 mais 
qui se met à 23.



```

Original issue reported on code.google.com by `guenil...@gmail.com` on 20 Oct 2014 at 4:02

**Comment by guenillon** [comment]
La liste des tables à vérifier : 
* ban_banque
* cop_compteur
* pad_perimetre_adhesion
* par_parametre
* tpp_type_paiement
